version: '3'

services:

  db:
    container_name: app_db
    image: postgres:13.0-alpine
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: mypassword
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d

  app:
    container_name: app
    build:
      context: ./
    ports:
      - "5000:5000"
    expose:
      - 5000
    depends_on:
      - db